name: f200605110098_prak2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  hexcolor: ^2.0.7
  persistent_bottom_nav_bar: ^5.0.2
  google_fonts: ^3.0.1
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/tunjuk.jpg
    - assets/reja.jpeg
    - assets/gdsc.png
    - assets/kepa.jpg
    - assets/lewandowski.jpg
    - assets/marcoreus.jpg
    - assets/mtf.jpg
    - assets/gdsc.svg
